// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8mgzCzD5iOQ6bTGbV5u4PPmrJFTihQ1o',
    appId: '1:961068593546:web:c5b2fc5bbbe28d7fe7d873',
    messagingSenderId: '961068593546',
    projectId: 'foodapp-3c0da',
    authDomain: 'foodapp-3c0da.firebaseapp.com',
    storageBucket: 'foodapp-3c0da.firebasestorage.app',
    measurementId: 'G-GK6J8CZWFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYBPLX1L-TFlxRKk0HApwmasUtcimVnL4',
    appId: '1:961068593546:android:86cadc8c1000430ae7d873',
    messagingSenderId: '961068593546',
    projectId: 'foodapp-3c0da',
    storageBucket: 'foodapp-3c0da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrvyXpPov9XbG2lM-zoI9bM4G_eW5sYyM',
    appId: '1:961068593546:ios:2432814d12536169e7d873',
    messagingSenderId: '961068593546',
    projectId: 'foodapp-3c0da',
    storageBucket: 'foodapp-3c0da.firebasestorage.app',
    iosBundleId: 'com.example.flutterGetx',
  );
}
